# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-02 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conpanys',
            name='c_pwd',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
    ]
