# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-01 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('info', '0002_auto_20181031_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachin',
            name='x_status',
            field=models.CharField(default='0', max_length=1, verbose_name='宣讲会状态'),
        ),
    ]
