# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-08 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('info', '0002_auto_20181102_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='conpanys',
            name='c_business',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='营业执照'),
        ),
        migrations.AddField(
            model_name='conpanys',
            name='c_capital',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='注册资本'),
        ),
        migrations.AddField(
            model_name='conpanys',
            name='c_manage',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='经营范围'),
        ),
        migrations.AddField(
            model_name='conpanys',
            name='c_site',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='详细地址'),
        ),
        migrations.AddField(
            model_name='conpanys',
            name='c_time',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='注册时间'),
        ),
        migrations.AddField(
            model_name='conpanys',
            name='c_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='企业类型'),
        ),
        migrations.AlterField(
            model_name='conpanys',
            name='c_brief',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='企业简介'),
        ),
        migrations.AlterField(
            model_name='conpanys',
            name='c_city',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='所在地区'),
        ),
        migrations.AlterField(
            model_name='conpanys',
            name='c_industry',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='conpanys',
            name='c_linkman',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='法人代表'),
        ),
        migrations.AlterField(
            model_name='conpanys',
            name='c_name',
            field=models.CharField(max_length=64, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='conpanys',
            name='c_nature',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='企业性质'),
        ),
        migrations.AlterField(
            model_name='conpanys',
            name='c_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='conpanys',
            name='c_scale',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='企业规模'),
        ),
    ]
