# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-08 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('info', '0003_auto_20181108_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conpanys',
            name='c_business',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='营业执照'),
        ),
        migrations.AlterField(
            model_name='conpanys',
            name='c_manage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='经营范围'),
        ),
    ]
