# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-09 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('info', '0005_auto_20181108_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conpanys',
            name='c_business',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='营业执照'),
        ),
    ]
