# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-09 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('info', '0006_auto_20181109_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conpanys',
            name='c_business',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='营业执照'),
        ),
    ]
